[env]
FNOX_AGE_KEY_FILE = "~/.ssh/Personal SSH Key"

[settings]
idiomatic_version_file_enable_tools = ["ruby"]
ruby = { compile = true }
status = { missing_tools = "always" }

[tools]
age = "latest"
aws-cli = { version = "latest", symlink_bins = "true" }
biome = "latest"
codex = "latest"
delta = "latest"
difftastic = "latest"
elasticsearch = "7"
elixir = "latest"
erlang = "latest"
fnox = "latest"
fzf = "latest"
gh = "latest"
go = "latest"
lazydocker = "latest"
lazygit = "latest"
lsd = "latest"
node = "lts"
pi = "latest"
ruby = { version = "latest", depends = ["rust"] }
rust = { version = "latest", components = "rust-analyzer,rust-src" }
starship = { version = "latest", postinstall = "starship preset pure-preset -o ~/.config/starship.toml" }
usage = "latest"
zoxide = "latest"

# Node.js
"npm:@herb-tools/language-server" = "latest"
"npm:agent-browser" = "latest"
