default_provider = "onepass"

[daemon]
enabled = true
idle_timeout = "8h"

[providers.onepass]
type = "1password"
vault = "Development"
account = "my.1password.com"

[secrets]
APP_SIGNAL_MCP_TOKEN = { provider = "onepass", value = "APP_SIGNAL_MCP_TOKEN/credential" }
FRESHDESK_API_KEY = { provider = "onepass" , value = "FRESHDESK_API_KEY" }
KAGI_API_KEY = { provider = "onepass", value = "KAGI_API_KEY/credential" }
CLOUDFLARE_ACCOUNT_ID = { provider = "onepass", value = "CLOUDFLARE_ACCOUNT_ID/credential" }
CLOUDFLARE_API_KEY = { provider = "onepass", value = "CLOUDFLARE_API_KEY/credential" }
CLOUDFLARE_GATEWAY_ID = { provider = "onepass", value = "CLOUDFLARE_GATEWAY_ID/credential" }
