# Resolved commits used by agent-skills install.

[[skills]]
name = "agent-browser"
repo = "https://github.com/vercel-labs/agent-browser.git"
path = "skills/agent-browser"
ref = "main"
resolved = "dcbe3522f931d24f85a786ba6ba7f343d86f7294"


[[skills]]
name = "github"
repo = "https://github.com/mitsuhiko/agent-stuff.git"
path = "skills/github"
ref = "main"
resolved = "4bce45560fa55ace2f5dc8634a63a2af464ddc8b"


[[skills]]
name = "domain-modeling"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/engineering/domain-modeling"
ref = "main"
resolved = "66898f60e8c744e269f8ce06c2b2b99ce7660d5f"


[[skills]]
name = "grilling"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/productivity/grilling"
ref = "main"
resolved = "66898f60e8c744e269f8ce06c2b2b99ce7660d5f"


[[skills]]
name = "grill-me"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/productivity/grill-me"
ref = "main"
resolved = "66898f60e8c744e269f8ce06c2b2b99ce7660d5f"


[[skills]]
name = "handoff"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/productivity/handoff"
ref = "main"
resolved = "66898f60e8c744e269f8ce06c2b2b99ce7660d5f"


[[skills]]
name = "teach"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/productivity/teach"
ref = "main"
resolved = "66898f60e8c744e269f8ce06c2b2b99ce7660d5f"


[[skills]]
name = "writing-great-skills"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/productivity/writing-great-skills"
ref = "main"
resolved = "66898f60e8c744e269f8ce06c2b2b99ce7660d5f"


[[skills]]
name = "grill-with-docs"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/engineering/grill-with-docs"
ref = "main"
resolved = "66898f60e8c744e269f8ce06c2b2b99ce7660d5f"


[[skills]]
name = "improve-codebase-architecture"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/engineering/improve-codebase-architecture"
ref = "main"
resolved = "66898f60e8c744e269f8ce06c2b2b99ce7660d5f"

