# Resolved commits used by agent-skills install.

[[skills]]
name = "agent-browser"
repo = "https://github.com/vercel-labs/agent-browser.git"
path = "skills/agent-browser"
ref = "main"
resolved = "eb05921bad874cd2a1b4fa5d1149f1ed26576cae"


[[skills]]
name = "github"
repo = "https://github.com/mitsuhiko/agent-stuff.git"
path = "skills/github"
ref = "main"
resolved = "3c891a9640f80c271ccc666ab7a39f9811bc3fb6"


[[skills]]
name = "domain-modeling"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/engineering/domain-modeling"
ref = "main"
resolved = "6654f6b60cd9d5be8b54c6fafe44346dabeb3b76"


[[skills]]
name = "grilling"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/productivity/grilling"
ref = "main"
resolved = "6654f6b60cd9d5be8b54c6fafe44346dabeb3b76"


[[skills]]
name = "grill-me"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/productivity/grill-me"
ref = "main"
resolved = "6654f6b60cd9d5be8b54c6fafe44346dabeb3b76"


[[skills]]
name = "handoff"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/productivity/handoff"
ref = "main"
resolved = "6654f6b60cd9d5be8b54c6fafe44346dabeb3b76"


[[skills]]
name = "teach"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/productivity/teach"
ref = "main"
resolved = "6654f6b60cd9d5be8b54c6fafe44346dabeb3b76"


[[skills]]
name = "grill-with-docs"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/engineering/grill-with-docs"
ref = "main"
resolved = "6654f6b60cd9d5be8b54c6fafe44346dabeb3b76"


[[skills]]
name = "improve-codebase-architecture"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/engineering/improve-codebase-architecture"
ref = "main"
resolved = "6654f6b60cd9d5be8b54c6fafe44346dabeb3b76"


[[skills]]
name = "writing-for-agents"
repo = "https://github.com/mattpocock/skills.git"
path = "skills/productivity/writing-for-agents"
ref = "main"
resolved = "6654f6b60cd9d5be8b54c6fafe44346dabeb3b76"

